export const metadata = {
  title: "Add Product | MNA",
  description: "Generated by create next app @mahmud",
};

const AddProductPage = () => {
  return <div>Add Product Page</div>;
};

export default AddProductPage;
