export const metadata = {
  title: "Manage Product | MNA",
  description: "Generated by create next app @mahmud",
};

const ManageProductPage = () => {
  return <div>Manage Product Page</div>;
};

export default ManageProductPage;
