export const metadata = {
  title: "Profile | MNA",
  description: "Generated by create next app @mahmud",
};
const ProfilePage = () => {
  return <div>Profile Page</div>;
};

export default ProfilePage;
