export const metadata = {
  title: "Dashboard | MNA",
  description: "Generated by create next app @mahmud",
};

const DashboardPage = () => {
  return <div>DashboardPage</div>;
};

export default DashboardPage;
